apiVersion: apps/v1

kind: ReplicaSet

metadata:
  name: myapp-rc
  labels:
    app: myapp-rc
    type: frontend

spec:
  selector:
    matchLabels:
      type: frontend
  template:
    metadata:
      name: myapp-pod
      labels:
        app: myapp
        type: frontend
        author: marinhofv

    spec:
      containers:
        - name: nginx-container
          image: nginx
          resources:
            limits:
              memory: 200Mi
              cpu: 500m
