apiVersion: v1

kind: Pod

metadata:
  name: myapp-pod
  labels:
    app: myapp
    type: frontend
    author: marinhofv

spec:
  containers:
    - name: nginx-container
      image: nginx
      resources:
        limits:
          memory: 200Mi
          cpu: 500m
