apiVersion: v1

kind: Service

metadata:
  name: voting-service
  labels:
    app: demo-voting-app

spec:
  type: NodePort
  selector:
    name: voting-app-pod
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001
