apiVersion: apps/v1

kind: Deployment

metadata:
  name: postgres-deploy
  labels:
    app: demo-voting-app

spec:
  replicas: 1
  selector:
    matchLabels:
      name: postgres-pod
  template:
    metadata:
      name: postgres-pod
      labels:
        name: postgres-pod
        app: demo-voting-app

    spec:
      containers:
        - name: postgres-pod
          image: postgres:9.4
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: POSTGRES_HOST_AUTH_METHOD
              value: trust
          ports:
            - containerPort: 5432
