apiVersion: apps/v1

kind: Deployment

metadata:
  name: result-deployment
  labels:
    app: demo-voting-app

spec:
  replicas: 1
  selector:
    matchLabels:
      name: result-app-pod
  template:
    metadata:
      name: result-app-pod
      labels:
        name: result-app-pod
        app: demo-voting-app

    spec:
      containers:
        - name: result-app-pod
          image: dockersamples/examplevotingapp_result
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
          ports:
            - containerPort: 80
