apiVersion: apps/v1

kind: Deployment

metadata:
  name: myapp

spec:
  selector:
    matchLabels:
      type: frontend

  template:
    metadata:
      labels:
        app: myapp
        type: frontend

    spec:
      containers:
        - name: myapp
          image: nginx
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
